# Generated by Django 5.2 on 2025-04-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='measurements.airqualitymeasurement')),
            ],
        ),
    ]
