# Generated by Django 5.2 on 2025-04-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0003_anomalylog_reason'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalylog',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='measurements.airqualitymeasurement'),
        ),
    ]
