# Generated by Django 5.2 on 2025-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0004_alter_anomalylog_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalylog',
            name='average_24h_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='exceeded_by',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
