services:
  web:
    build: ./backend
    command: ./wait-for-db.sh python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - rabbitmq
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app

  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: airuser
      POSTGRES_PASSWORD: airpass
      POSTGRES_DB: airquality
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  worker:
    build: ./backend
    command: python worker.py
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./backend:/code

volumes:
  postgres_data:
