# Generated by Django 5.2 on 2025-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalylog',
            name='parameter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
