# Generated by Django 5.2 on 2025-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0002_anomalylog_parameter_anomalylog_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalylog',
            name='reason',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
